<script setup lang="ts">
/* eslint-disable @typescript-eslint/no-explicit-any -- API detail shape is generated by Drizzle relations. */
import { fromJakartaInput, formatJakartaDateTime, isValidJakartaInput, toJakartaInput } from '~/utils/datetime'

const route = useRoute()
const { confirm } = useConfirm()
const eventId = computed(() => String(route.params.id))
const { data, pending, refresh } = await useFetch<any>(() => `/api/exam-events/${eventId.value}`)
const ev = computed(() => data.value?.data)
const tab = ref<'sesi' | 'mapel' | 'kelas'>('sesi')
const errorMessage = ref(''); const okMessage = ref('')

const { data: subjectsList } = await useFetch<{ data: any[] }>('/api/subjects')
const { data: classesList } = await useFetch<{ data: any[] }>('/api/classes')

// Total sesi (mapel × kelas) yang benar-benar dibuat untuk event ini.
const sessionCount = computed(() => (ev.value?.sessions?.length ?? ev.value?.sesi?.length ?? 0))

const stats = computed(() => [
  { label: 'Sesi Waktu', value: ev.value?.sesi?.length ?? 0, icon: 'heroicons:clock', tone: 'text-emerald-600 bg-emerald-50 dark:bg-emerald-400/10 dark:text-emerald-300' },
  { label: 'Mapel', value: ev.value?.subjects?.length ?? 0, icon: 'heroicons:book-open', tone: 'text-indigo-600 bg-indigo-50 dark:bg-indigo-400/10 dark:text-indigo-300' },
  { label: 'Kelas Peserta', value: ev.value?.classes?.length ?? 0, icon: 'heroicons:building-library', tone: 'text-violet-600 bg-violet-50 dark:bg-violet-400/10 dark:text-violet-300' },
  { label: 'Jadwal Ujian', value: sessionCount, icon: 'heroicons:calendar-days', tone: 'text-amber-600 bg-amber-50 dark:bg-amber-400/10 dark:text-amber-300' },
])

// ---- Sesi ----
const sesiModal = ref(false); const sesiForm = reactive({ id: '', name: '', openDate: '', openTime: '', closeDate: '', closeTime: '' })
function splitInput(value: string) { const [date, time] = toJakartaInput(value).split(' '); return { date: date ?? '', time: time?.slice(0, 5) ?? '' } }
function joinInput(date: string, time: string) { return `${date} ${time}` }
function openSesi(s?: any) { if (s) { const o = splitInput(s.openAt); const c = splitInput(s.closeAt); Object.assign(sesiForm, { id: s.id, name: s.name, openDate: o.date, openTime: o.time, closeDate: c.date, closeTime: c.time }) } else Object.assign(sesiForm, { id: '', name: `Sesi ${(ev.value?.sesi?.length ?? 0) + 1}`, openDate: '', openTime: '', closeDate: '', closeTime: '' }); sesiModal.value = true }
function formatJakarta(v: string) { return formatJakartaDateTime(v) }
async function saveSesi() { try { const openAt = joinInput(sesiForm.openDate, sesiForm.openTime); const closeAt = joinInput(sesiForm.closeDate, sesiForm.closeTime); if (!isValidJakartaInput(openAt) || !isValidJakartaInput(closeAt)) throw new Error('Pilih tanggal dan waktu ujian yang valid'); if (new Date(openAt.replace(' ', 'T')).getTime() >= new Date(closeAt.replace(' ', 'T')).getTime()) throw new Error('Waktu tutup harus setelah waktu buka'); const body = { name: sesiForm.name, openAt: fromJakartaInput(openAt), closeAt: fromJakartaInput(closeAt) }; if (sesiForm.id) await $fetch(`/api/exam-events/${eventId.value}/sesi/${sesiForm.id}`, { method: 'PATCH', body }); else await $fetch(`/api/exam-events/${eventId.value}/sesi`, { method: 'POST', body }); sesiModal.value = false; await refresh() } catch (e: any) { errorMessage.value = e?.data?.statusMessage || e?.message || 'Gagal menyimpan sesi' } }
async function delSesi(id: string) { if (!await confirm({ title: 'Hapus sesi?', message: 'Hapus sesi ini?', confirmLabel: 'Ya, hapus', tone: 'danger' })) return; try { await $fetch(`/api/exam-events/${eventId.value}/sesi/${id}`, { method: 'DELETE' }); await refresh() } catch (e: any) { errorMessage.value = e?.data?.statusMessage || 'Gagal menghapus sesi' } }

// ---- Mapel ----
const mapelModal = ref(false); const mapelForm = reactive<any>({ subjectId: '', sesiId: '', classIds: [] as string[], teacherIds: [], passingGrade: 75, durationMinutes: 90, maxAttempts: 1, shuffleQuestions: false, shuffleOptions: false, tokenRotationMinutes: null })
function openMapel() { Object.assign(mapelForm, { subjectId: '', sesiId: ev.value?.sesi?.[0]?.id ?? '', classIds: (ev.value?.classes ?? []).map((item: any) => item.classId), teacherIds: [], passingGrade: 75, durationMinutes: 90, maxAttempts: 1, shuffleQuestions: false, shuffleOptions: false, tokenRotationMinutes: null }); mapelModal.value = true }
async function saveMapel() { try { await $fetch(`/api/exam-events/${eventId.value}/subjects`, { method: 'POST', body: mapelForm }); mapelModal.value = false; await refresh() } catch (e: any) { errorMessage.value = e?.data?.statusMessage || 'Gagal menambah mapel' } }

// ---- Kelas ----
const kelasModal = ref(false); const selectedClasses = ref<string[]>([])
function openKelas() { selectedClasses.value = []; kelasModal.value = true }
async function saveKelas() { try { await $fetch(`/api/exam-events/${eventId.value}/classes`, { method: 'POST', body: { classIds: selectedClasses.value } }); kelasModal.value = false; await refresh() } catch (e: any) { errorMessage.value = e?.data?.statusMessage || 'Gagal menambah kelas' } }

// ---- Publish ----
const publishing = ref(false)
async function publish() { if (!await confirm({ title: 'Publikasikan event?', message: 'Ujian akan tampil untuk siswa.', confirmLabel: 'Publikasikan' })) return; publishing.value = true; errorMessage.value = ''; okMessage.value = ''; try { await $fetch(`/api/exam-events/${eventId.value}/publish`, { method: 'POST' }); okMessage.value = 'Event berhasil dipublikasikan.'; await refresh() } catch (e: any) { errorMessage.value = e?.data?.statusMessage || 'Gagal mempublikasikan' } finally { publishing.value = false } }

const availableSubjects = computed(() => (subjectsList.value?.data ?? []).filter((s) => !(ev.value?.subjects ?? []).some((x: any) => x.subjectId === s.id)))
const availableClasses = computed(() => (classesList.value?.data ?? []).filter((c) => !(ev.value?.classes ?? []).some((x: any) => x.classId === c.id)))
const statusLabel: Record<string, string> = { draft: 'Draft', published: 'Terbit', closed: 'Selesai' }
const statusTone: Record<string, string> = {
  draft: 'bg-amber-50 text-amber-700 dark:bg-amber-400/10 dark:text-amber-300',
  published: 'bg-emerald-50 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300',
  closed: 'bg-slate-100 text-slate-600 dark:bg-slate-700 dark:text-slate-300',
}
const tabs = [
  { key: 'sesi', label: 'Sesi', icon: 'heroicons:clock' },
  { key: 'mapel', label: 'Mapel & Soal', icon: 'heroicons:book-open' },
  { key: 'kelas', label: 'Kelas Peserta', icon: 'heroicons:building-library' },
] as const
</script>

<template>
  <div class="mx-auto max-w-6xl space-y-6 pb-8">
    <NuxtLink to="/dashboard/exams" class="inline-flex items-center gap-1.5 text-sm font-medium text-slate-500 transition hover:text-slate-700 dark:text-slate-400 dark:hover:text-slate-200">
      <Icon name="heroicons:arrow-left" class="h-4 w-4" /> Kembali ke daftar ujian
    </NuxtLink>

    <div v-if="pending" class="h-40 animate-pulse rounded-3xl bg-slate-100 dark:bg-slate-700/50" />

    <template v-else-if="ev">
      <!-- ============ HERO / HEADER ============ -->
      <section class="relative overflow-hidden rounded-3xl border border-slate-200/80 bg-white p-6 shadow-sm dark:border-slate-700 dark:bg-slate-800 sm:p-8">
        <div class="pointer-events-none absolute -right-16 -top-20 h-56 w-56 rounded-full bg-emerald-500/10 blur-3xl" />
        <div class="relative flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between">
          <div class="max-w-2xl">
            <div class="inline-flex items-center gap-2 rounded-full border border-emerald-100 bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700 dark:border-emerald-900/50 dark:bg-emerald-400/10 dark:text-emerald-300">
              <Icon name="heroicons:beaker" class="h-4 w-4" /> {{ ev.type }}
            </div>
            <h1 class="mt-4 text-3xl font-bold tracking-tight text-slate-900 dark:text-white">{{ ev.name }}</h1>
            <p class="mt-2 text-sm leading-relaxed text-slate-500 dark:text-slate-400">Semester {{ ev.semester }} · {{ ev.academicYear }} · {{ ev.startDate }} — {{ ev.endDate }}</p>
            <p v-if="ev.description" class="mt-2 text-sm text-slate-500 dark:text-slate-400">{{ ev.description }}</p>
          </div>
          <div class="flex flex-wrap items-center gap-2">
            <span class="inline-flex items-center gap-1.5 rounded-full px-3 py-1.5 text-xs font-semibold" :class="statusTone[ev.status] || statusTone.closed">
              <span class="h-1.5 w-1.5 rounded-full bg-current" />{{ statusLabel[ev.status] || ev.status }}
            </span>
            <button v-if="ev.status === 'draft'" class="inline-flex items-center gap-2 rounded-xl bg-emerald-500 px-5 py-2.5 text-sm font-semibold text-white shadow-lg shadow-emerald-500/20 transition hover:bg-emerald-600 disabled:opacity-50" :disabled="publishing" @click="publish">
              <Icon v-if="publishing" name="heroicons:arrow-path" class="h-4 w-4 animate-spin" />
              <Icon v-else name="heroicons:paper-airplane" class="h-4 w-4" />
              {{ publishing ? 'Memproses...' : 'Publikasikan' }}
            </button>
          </div>
        </div>

        <!-- Statistik ringkas -->
        <div class="relative mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">
          <div v-for="stat in stats" :key="stat.label" class="rounded-2xl border border-slate-100 bg-slate-50/60 p-4 dark:border-slate-700 dark:bg-slate-900/30">
            <div class="flex items-center justify-between">
              <span class="text-xs font-medium text-slate-500 dark:text-slate-400">{{ stat.label }}</span>
              <span class="flex h-8 w-8 items-center justify-center rounded-lg" :class="stat.tone">
                <Icon :name="stat.icon" class="h-4 w-4" />
              </span>
            </div>
            <p class="mt-2 text-2xl font-bold text-slate-900 dark:text-white">{{ stat.value }}</p>
          </div>
        </div>
      </section>

      <p v-if="errorMessage" class="flex items-center gap-2 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700 dark:border-red-900 dark:bg-red-900/20 dark:text-red-300">
        <Icon name="heroicons:exclamation-circle" class="h-4 w-4 shrink-0" /> {{ errorMessage }}
      </p>
      <p v-if="okMessage" class="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700 dark:border-emerald-900 dark:bg-emerald-900/20 dark:text-emerald-300">
        <Icon name="heroicons:check-circle" class="h-4 w-4 shrink-0" /> {{ okMessage }}
      </p>

      <!-- ============ TAB ============ -->
      <div class="flex flex-wrap gap-2">
        <button
          v-for="t in tabs"
          :key="t.key"
          class="inline-flex items-center gap-2 rounded-xl border px-3.5 py-2 text-sm font-medium transition"
          :class="tab === t.key
            ? 'border-emerald-500 bg-emerald-50 text-emerald-700 dark:border-emerald-600 dark:bg-emerald-400/10 dark:text-emerald-300'
            : 'border-slate-200 bg-white text-slate-600 hover:bg-slate-50 dark:border-slate-600 dark:bg-slate-800 dark:text-slate-300 dark:hover:bg-slate-700'"
          @click="tab = t.key"
        >
          <Icon :name="t.icon" class="h-4 w-4" /> {{ t.label }}
        </button>
      </div>

      <!-- SESI -->
      <section v-if="tab === 'sesi'" class="space-y-3">
        <div class="flex items-center justify-between">
          <h2 class="font-semibold text-slate-800 dark:text-slate-100">Sesi Ujian</h2>
          <button class="inline-flex items-center gap-2 rounded-xl bg-emerald-500 px-4 py-2 text-sm font-semibold text-white transition hover:bg-emerald-600" @click="openSesi()">
            <Icon name="heroicons:plus" class="h-4 w-4" /> Sesi
          </button>
        </div>
        <div v-if="!ev.sesi?.length" class="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center dark:border-slate-600 dark:bg-slate-800">
          <Icon name="heroicons:clock" class="mx-auto h-10 w-10 text-slate-300 dark:text-slate-600" />
          <p class="mt-3 text-sm text-slate-500 dark:text-slate-400">Belum ada sesi. Tambahkan gelombang waktu ujian.</p>
        </div>
        <article v-for="s in ev.sesi" :key="s.id" class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:border-emerald-300 dark:border-slate-700 dark:bg-slate-800 dark:hover:border-emerald-700">
          <div class="flex flex-wrap items-start justify-between gap-3">
            <div class="min-w-0">
              <h3 class="font-semibold text-slate-800 dark:text-slate-100">{{ s.name }}</h3>
              <p class="mt-1 inline-flex items-center gap-1.5 text-xs text-slate-500 dark:text-slate-400"><Icon name="heroicons:calendar-days" class="h-3.5 w-3.5" /> {{ formatJakarta(s.openAt) }} — {{ formatJakarta(s.closeAt) }}</p>
              <div class="mt-2 flex flex-wrap items-center gap-2 text-xs">
                <span class="rounded-full bg-slate-100 px-2.5 py-1 font-semibold text-slate-600 dark:bg-slate-700 dark:text-slate-300">{{ s.subjects?.length || 0 }} mapel</span>
                <span class="inline-flex items-center gap-1.5 rounded-full bg-indigo-50 px-2.5 py-1 font-semibold text-indigo-600 dark:bg-indigo-400/10 dark:text-indigo-300">
                  <Icon name="heroicons:key" class="h-3.5 w-3.5" /> Token proktor: <code class="font-mono">{{ s.proctorTokenPlain || '-' }}</code>
                </span>
              </div>
            </div>
            <div class="flex items-center gap-1">
              <NuxtLink :to="`/dashboard/exams/${eventId}/sesi/${s.id}`" class="inline-flex items-center gap-1.5 rounded-lg bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-700 transition hover:bg-slate-200 dark:bg-slate-700 dark:text-slate-200 dark:hover:bg-slate-600">
                <Icon name="heroicons:eye" class="h-4 w-4" /> Monitoring
              </NuxtLink>
              <button class="rounded-lg px-2.5 py-1.5 text-xs font-semibold text-blue-600 transition hover:bg-blue-50 dark:text-blue-400 dark:hover:bg-blue-900/20" @click="openSesi(s)">Edit</button>
              <button class="rounded-lg px-2.5 py-1.5 text-xs font-semibold text-red-500 transition hover:bg-red-50 dark:hover:bg-red-900/20" @click="delSesi(s.id)">Hapus</button>
            </div>
          </div>
        </article>
      </section>

      <!-- MAPEL -->
      <section v-else-if="tab === 'mapel'" class="space-y-3">
        <div class="flex items-center justify-between">
          <h2 class="font-semibold text-slate-800 dark:text-slate-100">Mapel & Soal</h2>
          <button class="inline-flex items-center gap-2 rounded-xl bg-emerald-500 px-4 py-2 text-sm font-semibold text-white transition hover:bg-emerald-600 disabled:opacity-50" :disabled="!ev.sesi?.length" @click="openMapel">
            <Icon name="heroicons:plus" class="h-4 w-4" /> Mapel
          </button>
        </div>
        <div v-if="!ev.sesi?.length" class="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-700 dark:border-amber-900 dark:bg-amber-900/20 dark:text-amber-300">
          Tambahkan sesi terlebih dahulu sebelum menambahkan mapel.
        </div>
        <div v-if="!ev.subjects?.length" class="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center dark:border-slate-600 dark:bg-slate-800">
          <Icon name="heroicons:book-open" class="mx-auto h-10 w-10 text-slate-300 dark:text-slate-600" />
          <p class="mt-3 text-sm text-slate-500 dark:text-slate-400">Belum ada mapel. Tambahkan mapel yang diujikan.</p>
        </div>
        <article v-for="s in ev.subjects" :key="s.id" class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:border-emerald-300 dark:border-slate-700 dark:bg-slate-800 dark:hover:border-emerald-700">
          <div class="flex flex-wrap items-start justify-between gap-3">
            <div class="min-w-0">
              <h3 class="font-semibold text-slate-800 dark:text-slate-100">{{ s.subject?.name }}</h3>
              <div class="mt-2 flex flex-wrap items-center gap-2 text-xs font-semibold">
                <span class="rounded-full bg-emerald-50 px-2.5 py-1 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300">KKM {{ s.passingGrade }}</span>
                <span class="rounded-full bg-slate-100 px-2.5 py-1 text-slate-600 dark:bg-slate-700 dark:text-slate-300">{{ s.durationMinutes }} menit</span>
                <span class="rounded-full bg-slate-100 px-2.5 py-1 text-slate-600 dark:bg-slate-700 dark:text-slate-300">Maks {{ s.maxAttempts }} percobaan</span>
                <span class="inline-flex items-center gap-1.5 rounded-full bg-indigo-50 px-2.5 py-1 text-indigo-600 dark:bg-indigo-400/10 dark:text-indigo-300">
                  <Icon name="heroicons:key" class="h-3.5 w-3.5" /> <code class="font-mono">{{ s.tokenPlain || '-' }}</code>
                </span>
              </div>
            </div>
            <NuxtLink :to="`/dashboard/exams/${eventId}/subjects/${s.id}`" class="inline-flex items-center gap-1.5 rounded-lg bg-slate-900 px-3.5 py-1.5 text-xs font-semibold text-white transition hover:bg-slate-700 dark:bg-slate-100 dark:text-slate-900 dark:hover:bg-white">
              Kelola Soal <Icon name="heroicons:arrow-right" class="h-3.5 w-3.5" />
            </NuxtLink>
          </div>
        </article>
      </section>

      <!-- KELAS -->
      <section v-else class="space-y-3">
        <div class="flex items-center justify-between">
          <h2 class="font-semibold text-slate-800 dark:text-slate-100">Kelas Peserta</h2>
          <button class="inline-flex items-center gap-2 rounded-xl bg-emerald-500 px-4 py-2 text-sm font-semibold text-white transition hover:bg-emerald-600 disabled:opacity-50" :disabled="!availableClasses.length" @click="openKelas">
            <Icon name="heroicons:plus" class="h-4 w-4" /> Kelas
          </button>
        </div>
        <div v-if="!ev.classes?.length" class="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center dark:border-slate-600 dark:bg-slate-800">
          <Icon name="heroicons:building-library" class="mx-auto h-10 w-10 text-slate-300 dark:text-slate-600" />
          <p class="mt-3 text-sm text-slate-500 dark:text-slate-400">Belum ada kelas peserta.</p>
        </div>
        <div v-else class="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">
          <div v-for="c in ev.classes" :key="c.classId" class="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-medium text-slate-700 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200">
            <Icon name="heroicons:building-library" class="h-4 w-4 text-emerald-600" /> {{ c.class?.name }}
          </div>
        </div>
      </section>
    </template>

    <!-- Modal Sesi -->
    <Teleport to="body">
      <div v-if="sesiModal" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4 backdrop-blur-sm" @click.self="sesiModal = false">
        <form class="w-full max-w-md overflow-hidden rounded-2xl bg-white shadow-2xl dark:bg-slate-800" @submit.prevent="saveSesi">
          <div class="flex items-center gap-3 border-b border-slate-100 px-6 py-5 dark:border-slate-700">
            <span class="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600 dark:bg-emerald-400/10 dark:text-emerald-300"><Icon name="heroicons:clock" class="h-5 w-5" /></span>
            <div><h2 class="font-bold text-slate-800 dark:text-slate-100">{{ sesiForm.id ? 'Edit' : 'Tambah' }} Sesi</h2><p class="text-xs text-slate-500 dark:text-slate-400">Atur rentang waktu ujian.</p></div>
          </div>
          <div class="space-y-4 px-6 py-5">
            <label class="block text-xs font-semibold uppercase tracking-wide text-slate-400">Nama sesi
              <input v-model="sesiForm.name" class="field mt-1.5" placeholder="Nama sesi" required>
            </label>
            <div class="grid grid-cols-2 gap-3">
              <label class="block text-xs font-semibold uppercase tracking-wide text-slate-400">Tanggal buka
                <input v-model="sesiForm.openDate" type="date" class="field mt-1.5" required>
              </label>
              <label class="block text-xs font-semibold uppercase tracking-wide text-slate-400">Jam buka
                <input v-model="sesiForm.openTime" type="time" class="field mt-1.5" required>
              </label>
            </div>
            <div class="grid grid-cols-2 gap-3">
              <label class="block text-xs font-semibold uppercase tracking-wide text-slate-400">Tanggal tutup
                <input v-model="sesiForm.closeDate" type="date" class="field mt-1.5" required>
              </label>
              <label class="block text-xs font-semibold uppercase tracking-wide text-slate-400">Jam tutup
                <input v-model="sesiForm.closeTime" type="time" class="field mt-1.5" required>
              </label>
            </div>
            <p class="text-[11px] text-slate-400">Gunakan picker tanggal dan waktu. Zona waktu mengikuti pengaturan sekolah.</p>
          </div>
          <div class="flex justify-end gap-2 border-t border-slate-100 px-6 py-4 dark:border-slate-700">
            <button type="button" class="rounded-xl border border-slate-200 px-4 py-2 text-sm font-medium text-slate-600 transition hover:bg-slate-50 dark:border-slate-600 dark:text-slate-300 dark:hover:bg-slate-700" @click="sesiModal = false">Batal</button>
            <button class="rounded-xl bg-emerald-500 px-5 py-2 text-sm font-semibold text-white transition hover:bg-emerald-600">Simpan</button>
          </div>
        </form>
      </div>
    </Teleport>

    <!-- Modal Mapel -->
    <Teleport to="body">
      <div v-if="mapelModal" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4 backdrop-blur-sm" @click.self="mapelModal = false">
        <form class="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white shadow-2xl dark:bg-slate-800" @submit.prevent="saveMapel">
          <div class="flex items-center gap-3 border-b border-slate-100 px-6 py-5 dark:border-slate-700">
            <span class="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600 dark:bg-emerald-400/10 dark:text-emerald-300"><Icon name="heroicons:book-open" class="h-5 w-5" /></span>
            <div><h2 class="font-bold text-slate-800 dark:text-slate-100">Tambah Mapel</h2><p class="text-xs text-slate-500 dark:text-slate-400">Pilih mapel, sesi, dan kelas peserta.</p></div>
          </div>
          <div class="space-y-4 px-6 py-5">
            <label class="block text-xs font-semibold uppercase tracking-wide text-slate-400">Mata pelajaran
              <select v-model="mapelForm.subjectId" class="field mt-1.5" required>
                <option value="" disabled>Pilih mapel</option>
                <option v-for="s in availableSubjects" :key="s.id" :value="s.id">{{ s.name }}</option>
              </select>
            </label>
            <label class="block text-xs font-semibold uppercase tracking-wide text-slate-400">Sesi
              <select v-model="mapelForm.sesiId" class="field mt-1.5" required>
                <option value="" disabled>Pilih sesi</option>
                <option v-for="s in ev?.sesi" :key="s.id" :value="s.id">{{ s.name }}</option>
              </select>
            </label>
            <div>
              <p class="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-400">Kelas peserta mapel</p>
              <div class="grid max-h-32 grid-cols-2 gap-2 overflow-y-auto">
                <label v-for="c in ev?.classes" :key="c.classId" class="flex items-center gap-2 text-sm text-slate-700 dark:text-slate-200">
                  <input v-model="mapelForm.classIds" type="checkbox" :value="c.classId" class="h-4 w-4 rounded border-slate-300 text-emerald-600 focus:ring-emerald-500"> {{ c.class?.name }}
                </label>
              </div>
            </div>
            <div class="grid grid-cols-3 gap-3">
              <label class="block text-xs font-semibold uppercase tracking-wide text-slate-400">KKM
                <input v-model.number="mapelForm.passingGrade" type="number" class="field mt-1.5">
              </label>
              <label class="block text-xs font-semibold uppercase tracking-wide text-slate-400">Durasi (menit)
                <input v-model.number="mapelForm.durationMinutes" type="number" class="field mt-1.5">
              </label>
              <label class="block text-xs font-semibold uppercase tracking-wide text-slate-400">Maks percobaan
                <input v-model.number="mapelForm.maxAttempts" type="number" class="field mt-1.5">
              </label>
            </div>
            <div class="flex flex-wrap gap-4 text-sm text-slate-700 dark:text-slate-200">
              <label class="flex items-center gap-2"><input v-model="mapelForm.shuffleQuestions" type="checkbox" class="h-4 w-4 rounded border-slate-300 text-emerald-600 focus:ring-emerald-500"> Acak soal</label>
              <label class="flex items-center gap-2"><input v-model="mapelForm.shuffleOptions" type="checkbox" class="h-4 w-4 rounded border-slate-300 text-emerald-600 focus:ring-emerald-500"> Acak opsi</label>
            </div>
          </div>
          <div class="flex justify-end gap-2 border-t border-slate-100 px-6 py-4 dark:border-slate-700">
            <button type="button" class="rounded-xl border border-slate-200 px-4 py-2 text-sm font-medium text-slate-600 transition hover:bg-slate-50 dark:border-slate-600 dark:text-slate-300 dark:hover:bg-slate-700" @click="mapelModal = false">Batal</button>
            <button class="rounded-xl bg-emerald-500 px-5 py-2 text-sm font-semibold text-white transition hover:bg-emerald-600">Simpan</button>
          </div>
        </form>
      </div>
    </Teleport>

    <!-- Modal Kelas -->
    <Teleport to="body">
      <div v-if="kelasModal" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4 backdrop-blur-sm" @click.self="kelasModal = false">
        <form class="w-full max-w-md overflow-hidden rounded-2xl bg-white shadow-2xl dark:bg-slate-800" @submit.prevent="saveKelas">
          <div class="flex items-center gap-3 border-b border-slate-100 px-6 py-5 dark:border-slate-700">
            <span class="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600 dark:bg-emerald-400/10 dark:text-emerald-300"><Icon name="heroicons:building-library" class="h-5 w-5" /></span>
            <div><h2 class="font-bold text-slate-800 dark:text-slate-100">Tambah Kelas Peserta</h2><p class="text-xs text-slate-500 dark:text-slate-400">Pilih kelas yang mengikuti ujian.</p></div>
          </div>
          <div class="max-h-64 space-y-2 overflow-y-auto px-6 py-5">
            <p v-if="!availableClasses.length" class="text-sm text-slate-500 dark:text-slate-400">Semua kelas sudah ditambahkan.</p>
            <label v-for="c in availableClasses" :key="c.id" class="flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm text-slate-700 dark:border-slate-600 dark:text-slate-200">
              <input v-model="selectedClasses" type="checkbox" :value="c.id" class="h-4 w-4 rounded border-slate-300 text-emerald-600 focus:ring-emerald-500">
              {{ c.name }} <span class="text-xs text-slate-400">({{ c.studentCount }} siswa)</span>
            </label>
          </div>
          <div class="flex justify-end gap-2 border-t border-slate-100 px-6 py-4 dark:border-slate-700">
            <button type="button" class="rounded-xl border border-slate-200 px-4 py-2 text-sm font-medium text-slate-600 transition hover:bg-slate-50 dark:border-slate-600 dark:text-slate-300 dark:hover:bg-slate-700" @click="kelasModal = false">Batal</button>
            <button class="rounded-xl bg-emerald-500 px-5 py-2 text-sm font-semibold text-white transition hover:bg-emerald-600 disabled:opacity-50" :disabled="!selectedClasses.length">Tambah</button>
          </div>
        </form>
      </div>
    </Teleport>
  </div>
</template>

<style scoped>
@reference "~/assets/css/tailwind.css";
.field { @apply w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm text-slate-800 outline-none transition focus:border-emerald-400 focus:ring-4 focus:ring-emerald-500/10 dark:border-slate-600 dark:bg-slate-800 dark:text-slate-200; }
</style>
