<script setup lang="ts">
// Student attendance is available through course logbook only.
type Row = { id: string; date: string; subjectName: string | null; subjectId?: string | null; status: string; note: string | null }
type Meta = { page: number; perPage: number; total: number; totalPages: number }
type Subject = { id: string; name: string }

const page = ref(1); const perPage = ref(50); const showCheckIn = ref(false); const selectedSubject = ref(''); const saving = ref(false); const message = ref(''); const formError = ref('')
const today = new Date().toISOString().slice(0, 10)
const { data, pending, error, refresh } = await useFetch<{ data: Row[]; studentId: string; summary: Record<string, number>; meta: Meta }>('/api/attendance', { query: { page, perPage }, watch: [page, perPage] })
const { data: subjectsData } = await useFetch<{ data: Subject[] }>('/api/subjects')
const subjects = computed(() => subjectsData.value?.data ?? [])
const meta = computed(() => data.value?.meta ?? { page: 1, perPage: 50, total: 0, totalPages: 1 }); const summary = computed(() => data.value?.summary ?? {})
const attendanceRate = computed(() => { const total = summary.value.total ?? 0; return total ? Math.round(((summary.value.present ?? 0) + (summary.value.late ?? 0)) / total * 100) : 0 })
watch(perPage, () => { page.value = 1 })
const label = (status: string) => ({ present: 'Hadir', late: 'Terlambat', excused: 'Izin', sick: 'Sakit', absent: 'Alpa' }[status] || status)
const color = (status: string) => ({ present: 'text-emerald-700 bg-emerald-50 dark:bg-emerald-400/10 dark:text-emerald-300', late: 'text-amber-700 bg-amber-50 dark:bg-amber-400/10 dark:text-amber-300', excused: 'text-blue-700 bg-blue-50 dark:bg-blue-400/10 dark:text-blue-300', sick: 'text-violet-700 bg-violet-50 dark:bg-violet-400/10 dark:text-violet-300', absent: 'text-rose-700 bg-rose-50 dark:bg-rose-400/10 dark:text-rose-300' }[status] || 'text-slate-600 bg-slate-100')
const formatDate = (date: string) => new Intl.DateTimeFormat('id-ID', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(`${date}T00:00:00`))
async function checkIn() { if (!selectedSubject.value || saving.value) return; saving.value = true; formError.value = ''; message.value = ''; try { await $fetch('/api/attendance', { method: 'POST', body: { studentId: data.value?.studentId, subjectId: selectedSubject.value, date: today, status: 'present', note: 'Absensi mandiri' } }); showCheckIn.value = false; selectedSubject.value = ''; message.value = 'Absensi berhasil direkam.'; await refresh() } catch (e: any) { formError.value = e.data?.statusMessage ?? 'Absensi gagal direkam.' } finally { saving.value = false } }
</script>

<template>
  <div class="space-y-6">
    <section class="relative overflow-hidden rounded-3xl bg-gradient-to-br from-indigo-600 via-violet-600 to-fuchsia-600 px-6 py-7 text-white shadow-xl shadow-indigo-200/40 dark:shadow-none sm:px-8"><div class="relative z-10 flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><div class="mb-3 inline-flex items-center gap-2 rounded-full bg-white/15 px-3 py-1 text-xs font-semibold ring-1 ring-white/20"><Icon name="heroicons:sparkles" /> Rekam akademik</div><h1 class="text-3xl font-bold tracking-tight">Absensi Saya</h1><p class="mt-2 max-w-lg text-sm text-indigo-100">Rekam kehadiran mandiri, pantau riwayat belajar.</p></div><div class="rounded-2xl bg-white/15 px-5 py-3 backdrop-blur-sm ring-1 ring-white/20"><p class="text-xs text-indigo-100">Tingkat kehadiran</p><p class="mt-1 text-3xl font-bold">{{ attendanceRate }}<span class="text-lg">%</span></p></div></div><div class="absolute -right-12 -top-16 h-48 w-48 rounded-full bg-white/10 blur-2xl" /></section>
    <div v-if="message" class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700 dark:border-emerald-900 dark:bg-emerald-400/10 dark:text-emerald-300">{{ message }}</div>
    <section class="rounded-2xl border border-indigo-100 bg-indigo-50/70 p-5 dark:border-indigo-900/50 dark:bg-indigo-400/10"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div class="flex items-center gap-2 font-bold text-slate-800 dark:text-slate-100"><Icon name="heroicons:hand-raised" class="text-indigo-600" /> Absensi hari ini</div><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Pilih mata pelajaran untuk mencatat kehadiran.</p></div><button class="inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-indigo-500/20 transition hover:bg-indigo-700" @click="showCheckIn = !showCheckIn"><Icon name="heroicons:check-badge" /> Rekam Kehadiran</button></div><div v-if="showCheckIn" class="mt-4 flex flex-col gap-3 sm:flex-row"><select v-model="selectedSubject" class="h-11 flex-1 rounded-xl border border-slate-200 bg-white px-3 text-sm dark:border-slate-600 dark:bg-slate-800"><option value="">Pilih mata pelajaran</option><option v-for="subject in subjects" :key="subject.id" :value="subject.id">{{ subject.name }}</option></select><button :disabled="saving || !selectedSubject" class="rounded-xl bg-emerald-600 px-5 py-2 text-sm font-semibold text-white disabled:opacity-50" @click="checkIn">{{ saving ? 'Menyimpan...' : 'Saya Hadir' }}</button></div><p v-if="formError" class="mt-2 text-sm text-rose-600">{{ formError }}</p></section>
    <section class="grid grid-cols-2 gap-3 sm:grid-cols-4"><div v-for="item in [{ label: 'Hadir', value: summary.present ?? 0, icon: 'check-circle', tone: 'emerald' }, { label: 'Terlambat', value: summary.late ?? 0, icon: 'clock', tone: 'amber' }, { label: 'Izin / Sakit', value: (summary.excused ?? 0) + (summary.sick ?? 0), icon: 'document-text', tone: 'violet' }, { label: 'Alpa', value: summary.absent ?? 0, icon: 'x-circle', tone: 'rose' }]" :key="item.label" class="rounded-2xl border border-slate-200/80 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-800"><div class="flex items-center justify-between"><span class="text-xs font-medium text-slate-500">{{ item.label }}</span><Icon :name="`heroicons:${item.icon}`" :class="`text-${item.tone}-500`" class="h-5 w-5" /></div><p class="mt-3 text-2xl font-bold text-slate-800 dark:text-slate-100">{{ item.value }}</p></div></section>
    <section class="overflow-hidden rounded-3xl border border-slate-200/80 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-800"><div class="flex items-center justify-between border-b border-slate-100 px-5 py-5 dark:border-slate-700"><div><h2 class="font-bold text-slate-800 dark:text-slate-100">Riwayat kehadiran</h2><p class="mt-1 text-xs text-slate-500">Detail absensi per mata pelajaran</p></div><select v-model="perPage" class="h-10 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm dark:border-slate-600 dark:bg-slate-700"><option :value="50">50 baris</option><option :value="100">100 baris</option><option :value="150">150 baris</option></select></div><div v-if="error" class="m-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">Gagal memuat absensi.</div><div v-else-if="pending" class="p-12 text-center text-sm text-slate-500">Memuat riwayat...</div><div v-else-if="!data?.data.length" class="p-12 text-center text-slate-500">Belum ada data absensi.</div><div v-else class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50/80 dark:bg-slate-700/40"><tr><th class="px-5 py-3.5 text-xs uppercase text-slate-500">Tanggal</th><th class="px-5 py-3.5 text-xs uppercase text-slate-500">Mata Pelajaran</th><th class="px-5 py-3.5 text-xs uppercase text-slate-500">Status</th><th class="px-5 py-3.5 text-xs uppercase text-slate-500">Catatan</th></tr></thead><tbody><tr v-for="row in data.data" :key="row.id" class="border-t border-slate-100 dark:border-slate-700"><td class="whitespace-nowrap px-5 py-4 font-medium text-slate-700 dark:text-slate-200">{{ formatDate(row.date) }}</td><td class="px-5 py-4 text-slate-600 dark:text-slate-300">{{ row.subjectName || 'Data lama' }}</td><td class="px-5 py-4"><span :class="['inline-flex items-center rounded-full px-2.5 py-1 text-xs font-semibold', color(row.status)]"><span class="mr-1.5 h-1.5 w-1.5 rounded-full bg-current" />{{ label(row.status) }}</span></td><td class="px-5 py-4 text-slate-500">{{ row.note || '-' }}</td></tr></tbody></table></div><div v-if="meta.totalPages > 1" class="flex items-center justify-between border-t border-slate-100 px-5 py-4 dark:border-slate-700"><span class="text-xs text-slate-500">{{ (meta.page - 1) * meta.perPage + 1 }}–{{ Math.min(meta.page * meta.perPage, meta.total) }} dari {{ meta.total }}</span><div class="flex gap-2"><button class="rounded-lg border px-3 py-2 text-xs disabled:opacity-40" :disabled="meta.page <= 1" @click="page--">Sebelumnya</button><span class="rounded-lg bg-indigo-50 px-3 py-2 text-xs text-indigo-600">{{ meta.page }} / {{ meta.totalPages }}</span><button class="rounded-lg border px-3 py-2 text-xs disabled:opacity-40" :disabled="meta.page >= meta.totalPages" @click="page++">Berikutnya</button></div></div></section>
  </div>
</template>